const apiResponse = {
    "errors": {
        "Amadeus": "Some error occured"
    },
    "current_depart_date_prices": [],
    "best_prices": [{
            "value": 6700,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T10:06:11",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-13",
            "actual": true
        },
        {
            "value": 5659,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-13T11:10:52",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-21",
            "actual": true
        },
        {
            "value": 6901,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-14T15:09:18",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-21",
            "actual": true
        },
        {
            "value": 7394,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Biletix",
            "found_at": "2019-10-12T18:17:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-14",
            "actual": true
        },
        {
            "value": 6750,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T14:30:31",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-12",
            "actual": true
        },
        {
            "value": 6574,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-12T19:55:53",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-17",
            "actual": true
        },
        {
            "value": 6750,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T03:57:49",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-04",
            "actual": true
        },
        {
            "value": 7597,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T15:53:39",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-26",
            "actual": true
        },
        {
            "value": 6235,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-11T07:42:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-08-02",
            "actual": true
        },
        {
            "value": 6637,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T18:01:32",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-08",
            "actual": true
        },
        {
            "value": 4088,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T12:14:13",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-11",
            "actual": true
        },
        {
            "value": 4451,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T07:48:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-13",
            "actual": true
        },
        {
            "value": 6331,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T08:50:28",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-29",
            "actual": true
        },
        {
            "value": 6853,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T19:30:11",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-06",
            "actual": true
        },
        {
            "value": 7679,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-11T11:12:54",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-03-11",
            "actual": true
        },
        {
            "value": 4675,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T15:24:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-06",
            "actual": true
        },
        {
            "value": 6700,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T12:35:00",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-28",
            "actual": true
        },
        {
            "value": 8396,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T12:30:53",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-14",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T18:34:21",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-16",
            "actual": true
        },
        {
            "value": 5083,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-11T18:32:09",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-10",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T14:52:22",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-25",
            "actual": true
        },
        {
            "value": 6577,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Vueling",
            "found_at": "2019-10-12T21:00:00",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-24",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T14:19:56",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-02",
            "actual": true
        },
        {
            "value": 14343,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T21:21:51",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-03",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T19:41:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-09-09",
            "actual": true
        },
        {
            "value": 6703,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T10:26:33",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-19",
            "actual": true
        },
        {
            "value": 6863,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "City.Travel",
            "found_at": "2019-10-14T07:13:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-08",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T13:25:54",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-01",
            "actual": true
        },
        {
            "value": 5512,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-11T10:51:52",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-17",
            "actual": true
        },
        {
            "value": 6049,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T17:05:03",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-09",
            "actual": true
        },
        {
            "value": 7327,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-13T16:40:13",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-11",
            "actual": true
        },
        {
            "value": 7739,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-12T16:35:59",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-15",
            "actual": true
        },
        {
            "value": 14296,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Aviakassa",
            "found_at": "2019-10-14T08:07:24",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-01",
            "actual": true
        },
        {
            "value": 13800,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T21:22:43",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-04",
            "actual": true
        },
        {
            "value": 6667,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T17:09:58",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-07",
            "actual": true
        },
        {
            "value": 6031,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T14:08:21",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-11",
            "actual": true
        },
        {
            "value": 6700,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T10:05:58",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-08-28",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T16:35:34",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-14",
            "actual": true
        },
        {
            "value": 6223,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-11T18:20:57",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-10",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T20:03:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-09",
            "actual": true
        },
        {
            "value": 14363,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T07:58:51",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-02",
            "actual": true
        },
        {
            "value": 5511,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-12T12:59:06",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-04",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T19:42:05",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-15",
            "actual": true
        },
        {
            "value": 7704,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-13T00:38:34",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-27",
            "actual": true
        },
        {
            "value": 6629,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-12T16:23:54",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-16",
            "actual": true
        },
        {
            "value": 7871,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T21:08:41",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-25",
            "actual": true
        },
        {
            "value": 6900,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T21:01:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-01",
            "actual": true
        },
        {
            "value": 4329,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-12T19:30:39",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-04",
            "actual": true
        },
        {
            "value": 4411,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T16:37:40",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-27",
            "actual": true
        },
        {
            "value": 12144,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T19:30:32",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-31",
            "actual": true
        },
        {
            "value": 6963,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T15:24:00",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-12",
            "actual": true
        },
        {
            "value": 9156,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T17:23:52",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-01",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T16:18:07",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-03-02",
            "actual": true
        },
        {
            "value": 6442,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-14T17:06:38",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-05",
            "actual": true
        },
        {
            "value": 4137,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T16:39:17",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-12",
            "actual": true
        },
        {
            "value": 5163,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T08:10:06",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-30",
            "actual": true
        },
        {
            "value": 6020,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T21:29:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-04",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T12:40:06",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-25",
            "actual": true
        },
        {
            "value": 6787,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "SuperSaver.ru",
            "found_at": "2019-10-12T09:08:32",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-08",
            "actual": true
        },
        {
            "value": 4892,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T03:48:03",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-29",
            "actual": true
        },
        {
            "value": 6076,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T16:59:00",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-06",
            "actual": true
        },
        {
            "value": 6901,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-14T18:01:11",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-12",
            "actual": true
        },
        {
            "value": 16409,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T08:04:39",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-28",
            "actual": true
        },
        {
            "value": 6939,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-14T15:04:33",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-06",
            "actual": true
        },
        {
            "value": 7883,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T20:09:56",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-02",
            "actual": true
        },
        {
            "value": 9156,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T21:02:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-27",
            "actual": true
        },
        {
            "value": 10906,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-13T19:35:02",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-05",
            "actual": true
        },
        {
            "value": 8229,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T20:20:09",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-31",
            "actual": true
        },
        {
            "value": 6339,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "City.Travel",
            "found_at": "2019-10-12T16:42:20",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-23",
            "actual": true
        },
        {
            "value": 6451,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T10:31:52",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-24",
            "actual": true
        },
        {
            "value": 13763,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T19:47:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-29",
            "actual": true
        },
        {
            "value": 6964,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-12T11:58:47",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-15",
            "actual": true
        },
        {
            "value": 6020,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T15:07:07",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-17",
            "actual": true
        },
        {
            "value": 6677,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T07:41:07",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-09-19",
            "actual": true
        },
        {
            "value": 4504,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-14T04:50:20",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-15",
            "actual": true
        },
        {
            "value": 5596,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-12T19:59:57",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-26",
            "actual": true
        },
        {
            "value": 6087,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T11:01:24",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-30",
            "actual": true
        },
        {
            "value": 5297,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-14T17:58:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-28",
            "actual": true
        },
        {
            "value": 7612,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T07:15:16",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-26",
            "actual": true
        },
        {
            "value": 6031,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T13:14:48",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-24",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T12:55:08",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-06",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T18:48:13",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-08",
            "actual": true
        },
        {
            "value": 5511,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-13T17:17:49",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-26",
            "actual": true
        },
        {
            "value": 6085,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T22:31:42",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-19",
            "actual": true
        },
        {
            "value": 5511,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-12T16:29:47",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-10",
            "actual": true
        },
        {
            "value": 6123,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-14T06:58:47",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-17",
            "actual": true
        },
        {
            "value": 6671,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-11T18:40:10",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-17",
            "actual": true
        },
        {
            "value": 6396,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T18:25:44",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-16",
            "actual": true
        },
        {
            "value": 7807,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "City.Travel",
            "found_at": "2019-10-14T16:50:01",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-18",
            "actual": true
        },
        {
            "value": 6750,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T10:54:00",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-15",
            "actual": true
        },
        {
            "value": 7814,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T17:33:22",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-01",
            "actual": true
        },
        {
            "value": 6227,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-13T14:32:39",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-26",
            "actual": true
        },
        {
            "value": 8029,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T18:32:46",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-15",
            "actual": true
        },
        {
            "value": 5512,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-14T06:02:58",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-03-25",
            "actual": true
        },
        {
            "value": 5512,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-11T11:43:47",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-11",
            "actual": true
        },
        {
            "value": 6964,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-12T12:35:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-14",
            "actual": true
        },
        {
            "value": 5659,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T20:27:52",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-14",
            "actual": true
        },
        {
            "value": 6862,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T11:12:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-03-23",
            "actual": true
        },
        {
            "value": 8430,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-13T15:39:31",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-26",
            "actual": true
        },
        {
            "value": 5079,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "SuperSaver.ru",
            "found_at": "2019-10-13T21:12:52",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-17",
            "actual": true
        },
        {
            "value": 6670,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T12:13:26",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-18",
            "actual": true
        },
        {
            "value": 5482,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T19:00:26",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-09",
            "actual": true
        },
        {
            "value": 6669,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T22:51:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-23",
            "actual": true
        },
        {
            "value": 6700,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T09:18:41",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-07",
            "actual": true
        },
        {
            "value": 6667,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T14:15:07",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-03",
            "actual": true
        },
        {
            "value": 6252,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T11:16:03",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-05",
            "actual": true
        },
        {
            "value": 5511,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-13T23:25:15",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-15",
            "actual": true
        },
        {
            "value": 10559,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "City.Travel",
            "found_at": "2019-10-14T13:58:06",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-02",
            "actual": true
        },
        {
            "value": 6667,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T20:16:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-28",
            "actual": true
        },
        {
            "value": 10565,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T18:45:41",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-30",
            "actual": true
        },
        {
            "value": 7864,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-12T23:49:28",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-23",
            "actual": true
        },
        {
            "value": 6677,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T20:46:27",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-09",
            "actual": true
        },
        {
            "value": 10509,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T21:31:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-01",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T10:22:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-30",
            "actual": true
        },
        {
            "value": 6853,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T09:27:24",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-09",
            "actual": true
        },
        {
            "value": 6155,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-13T16:50:48",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-18",
            "actual": true
        },
        {
            "value": 5954,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "JetCompass",
            "found_at": "2019-10-14T14:31:17",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-01",
            "actual": true
        },
        {
            "value": 5762,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T15:10:29",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-22",
            "actual": true
        },
        {
            "value": 7548,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-13T22:41:11",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-21",
            "actual": true
        },
        {
            "value": 6855,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T16:53:49",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-08-25",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T16:38:48",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-30",
            "actual": true
        },
        {
            "value": 6700,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T07:50:01",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-12",
            "actual": true
        },
        {
            "value": 7070,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "airBaltic",
            "found_at": "2019-10-12T19:43:43",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-19",
            "actual": true
        },
        {
            "value": 5511,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-13T21:34:40",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-10",
            "actual": true
        },
        {
            "value": 6853,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T19:29:06",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-24",
            "actual": true
        },
        {
            "value": 8040,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T15:44:23",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-25",
            "actual": true
        },
        {
            "value": 5219,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T09:08:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-22",
            "actual": true
        },
        {
            "value": 6703,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T10:36:58",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-04-20",
            "actual": true
        },
        {
            "value": 6660,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T12:23:46",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-09-24",
            "actual": true
        },
        {
            "value": 7837,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-11T06:51:56",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-07",
            "actual": true
        },
        {
            "value": 6859,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T06:31:54",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-21",
            "actual": true
        },
        {
            "value": 7688,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T05:52:44",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-03-06",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T19:03:38",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-05-07",
            "actual": true
        },
        {
            "value": 6853,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T12:12:43",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-23",
            "actual": true
        },
        {
            "value": 5509,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-11T08:08:17",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-03-30",
            "actual": true
        },
        {
            "value": 6678,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-12T19:58:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-11",
            "actual": true
        },
        {
            "value": 5154,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Kiwi.com",
            "found_at": "2019-10-12T20:02:37",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-10",
            "actual": true
        },
        {
            "value": 5512,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-14T07:55:51",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-22",
            "actual": true
        },
        {
            "value": 3438,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T18:17:48",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-18",
            "actual": true
        },
        {
            "value": 4249,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-14T19:46:22",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-01-30",
            "actual": true
        },
        {
            "value": 5511,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-12T09:08:46",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-03",
            "actual": true
        },
        {
            "value": 4635,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Kiwi.com",
            "found_at": "2019-10-12T22:03:45",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-20",
            "actual": true
        },
        {
            "value": 5512,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "OneTwoTrip",
            "found_at": "2019-10-11T16:25:59",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-04",
            "actual": true
        },
        {
            "value": 8162,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Mytrip.com",
            "found_at": "2019-10-13T11:25:42",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-24",
            "actual": true
        },
        {
            "value": 9206,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "City.Travel",
            "found_at": "2019-10-14T14:56:35",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-03",
            "actual": true
        },
        {
            "value": 6750,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-13T21:13:46",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-06-18",
            "actual": true
        },
        {
            "value": 6703,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T10:30:19",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-07-02",
            "actual": true
        },
        {
            "value": 7392,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 2,
            "gate": "Biletix",
            "found_at": "2019-10-14T21:04:12",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-30",
            "actual": true
        },
        {
            "value": 6667,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-14T14:42:55",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-04",
            "actual": true
        },
        {
            "value": 6711,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T11:36:54",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-11-19",
            "actual": true
        },
        {
            "value": 4725,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "KupiBilet.ru",
            "found_at": "2019-10-14T17:53:08",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-10-20",
            "actual": true
        },
        {
            "value": 5363,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Aviakassa",
            "found_at": "2019-10-14T17:59:38",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2019-12-13",
            "actual": true
        },
        {
            "value": 7622,
            "trip_class": 0,
            "show_to_affiliates": false,
            "return_date": null,
            "origin": "MOW",
            "number_of_changes": 1,
            "gate": "Trip.ru",
            "found_at": "2019-10-11T17:53:23",
            "distance": 2539,
            "destination": "NCE",
            "depart_date": "2020-02-03",
            "actual": true
        }
    ]
};

function checkDate(ticketDate) {
    return (ticketDate >= '2019-09-01') && (ticketDate <= '2019-11-30')
};
let minPrice = null;
for (let ticket of apiResponse.best_prices) {
    if ((checkDate(ticket.depart_date)) && ((minPrice > ticket.value) || (minPrice === null))) { minPrice = ticket.value; };
};

if (minPrice === null) {
    console.log("Билетов нет");
} else {
    console.log("Самый дешевый билет из Москвы в Ниццу на осень 2019г. стоит ", minPrice, " рублей");
};